### ISSUE TITLE
Dependencies management

### ISSUE THREAD

**Issue by LaG1924** [LaG1924/AltCraft#15]
The current build system requires significant refactoring.

I think that everything inside `/external/` should be replaced with a git-submodule or something similar.

**Comment by MrGooogo** [comment]
I actually seen a talk about modern cmake features not that long ago, it turns out they've got new module there(it's been there for a few years already actually, so i am not sure if it is even appropriate to call it "new", but it got a cosmetic make over not that long ago, so i assume it's still somewhat apropriate) for fetching sources external dependencies before build time. Here it is actually https://cmake.org/cmake/help/latest/module/FetchContent.html

This way we are not gonna be limited by git resources(as far as i am concerned cmake can fetch sources from svn and tarballs as well), it will make the building process that much simpler(aka developers don't need to update the submodules every time separately before building the project), it will be easier to migrate the project if need arises. It is also easier to manage dependencies that way, albeit subjectively.
