### ISSUE TITLE
Target glsl 110 version

### ISSUE THREAD

**Issue by abasgames** [LaG1924/AltCraft#48]
Target glsl 110 instead of 330 to be close to original minecraft 1.12.2 shader

**Comment by LaG1924** [comment]
https://www.minecraftforum.net/forums/support/java-edition-support/1864803-psa-minecraft-dropping-support-of-opengl-versions

![image](https://user-images.githubusercontent.com/12997935/90017084-73a33d00-dcc4-11ea-9ead-6fc6f3624d96.png)

**Comment by abasgames** [comment]
https://minecraft.gamepedia.com/Java_Edition_hardware_requirements
Also the latest version of Minecraft are still working under opengl 2.0 version fine

**Comment by abasgames** [comment]
Miecraft support opengl 2.0 since 
Minecraft 1.15 19w34a snapshot
https://www.minecraft.net/es-es/article/minecraft-snapshot-19w34a

**Comment by LaG1924** [comment]
Minecraft was originally developed with legacy technology.
This project will not support ancient technologies for the sake of greater performance, flexibility and graphics quality, although this is not yet so noticeable (right now, stable gameplay is more important than high resolution textures or advanced shadows).

Unfortunately, support for legacy shaders (fixed pipeline) will not be implemented in AltCraft (anytime soon), because this will require support for OpenGL 1/2 as well.
