### ISSUE TITLE
Graphics performance enhancement

### ISSUE THREAD

**Issue by uis246** [LaG1924/AltCraft#53]
1) Stop rendering when window minimized
2) Add simple section backfaces culling on CPU(store faces as 7 arrays of faces by their direction: up, down, east, north, west, south, none. "None" will not culled).This will avoid useless vertex shader and other pre-rasterization stages execution.
3) Make post-processing optional and render to fbo. This will enable Pixel Ownership Test.
4) Refactor world rendering. Split to opaque and transperent passes.
5) Use static uniform location for projection matrix and day time
6) Store chunk in single VBO

Also can be useful:
1) Indirect texturing
2) Store entire chunk in single vao for batching
3) GLX_INTEL_swap_event with GLX_OML_sync_control. Useful when GPU is bottleneck

**Comment by uis246** [comment]
3. Add simple section backfaces culling on CPU(store faces as 7 arrays of faces by their direction: up, down, east, north, west, south, none. "None" will not culled).This will prevent useless vertex shader execution.

**Comment by uis246** [comment]
4. Make post-processing optional and render to fbo. This will enable Pixel Ownership Test.

**Comment by LaG1924** [comment]
So, most of it should be fixed in #78. Other ones need to be discussed. Also, I will keep consistent numeration for more convenient sub-issues referencing.

1. Is it really necessary? Windows already gives lower (or even lowest) priority for non-focused windows, so it uses fewer resources. And sometimes high framerate for minimized windows can be useful.
2. I didn't get it. Do you mean something like #20? Please better explain your algorithm.
3. Pixel Ownership Test does not sound like something important, but anyway, this feature is implemented in a12779b
4. Opaque/masked faces could be split but its performance effort is doubtful. Blended/non-blended faces (AFAIK, in MC1.12.2 only water does need blending) must be split into two passes.
5. Fixed in c905ede556c892
6. It will decrease section (16x16x16 blocks) remeshing performance. We will need then spare space for removed/created new blocks.
7. I cannot google directly "Indirect texturing". Did you mean [Bindless Texture](https://www.khronos.org/opengl/wiki/Bindless_Texture)? Even if you don't, it (Bindless Textures) looks promising. Direct State Access sounds good too.
8. As noted in 6., it will ruin remeshing performance and will make CPU-culling (or GPGPU) almost impossible. Right now bottleneck is (as states Nvidia's NSight) VAF (vertex attribute fetch). In other words, there are too many vertices to process (which ones will be z-culled later anyway, so why do we have to send them to draw?).
9. Is it only Intel&Linux specific? If so, then better to find a more common subset of such functionality (if applicable, of course).
